require:
  - rubocop-rspec

# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.

#Example: https://github.com/bbatsov/rubocop/blob/master/config/default.yml

# Common configuration.
AllCops:
  Exclude:
    - "Gemfile"
    - "vendor/**/*"
    - "db/**/*"
    - "Rakefile"
    - "bin/update"
    - "bin/setup"
    - "frontend/**/*"
    - "scripts/**/*"

Style/Documentation:
  Enabled: false

RSpec/FilePath:
  Enabled: false
