version: "3"
services:
  app:
    env_file:
      - $ENV_FILE
    command: ["rackup", "--port", "9292", "--host", "0000"]
    volumes:
      - .:/app
    ports:
      - 9292:9292
    build:
      context: .
      dockerfile: ops/live.dockerfile
      args:
        DOCKER_REPOSITORY: omaik/kitten_store
    depends_on:
      - db
  db:
    image: postgres:10.13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass

volumes:
  postgres-data:
