pg: &pg
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  pool: 30

development:
  <<: *pg
  database: kittens_store_dev

test:
  <<: *pg
  database: kittens_store_test

production:
  <<: *pg
  database: kittens_store
