name: Rspec Parallel
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      database:
        image: postgres:12.1-alpine
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: pass
        ports:
          - '5432:5432'
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [2]
        #ci_node_total: [2]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0,1]
        #ci_node_index: [0,1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.9
          bundler: Gemfile.lock
      - name: Install dependencies
        run: |
          bundle config path ~/.bundle
          bundle install --jobs 4 --retry 3
      - name: Set up Database
        env:
          DATABASE_URL: postgresql://app:pass@localhost:5432/app_test
          RACK_ENV: test
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
      - name: Run Unit Tests
        # run: bundle exec rspec
        env:
          DATABASE_URL: postgresql://app:pass@localhost:5432/app_test
          RACK_ENV: test
          CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          CI_PARALLEL_TESTS: true
        run: bundle exec rake "knapsack:rspec[-f RspecJunitFormatter -o reports/rspec/report.xml -f documentation]"
